In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3]) #Array X
y = np.array([4,5,6]) #Array Y

In [7]:
np.concatenate([x,y]) #Concatenation (1D)

array([1, 2, 3, 4, 5, 6])

In [9]:
z = np.array([7,8,9])

**Concantenation for 2D Arrays:**

In [12]:
a = np.array ([[1,2,3],
               [4,5,6]]) #2D Array

In [13]:
b = np.array([[10,11,12],
              [13,14,15]])#2D Array

In [14]:
np.concatenate([a,b]) #by row based, axis = 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
np.concatenate([a,b], axis = 1 ) #by column based, axis = 1

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

Quote: The axis num is normally zero. So the concatenate function combines arrays by row based. If you want to combine arrays by column based, you have to change axis num to `1`.

The command `np.concatenate([a,b])` is same as this command `np.concatenate([a,b], axis = 0).` The axis num is normally 0 as you can see. This commands are combines arrays by columns.

In [18]:
#Hasan Baris GOK