In [5]:
import numpy as np #adding the numpy library as np

***Creating Arrays***

In [7]:
a = np.array([1,2,3]) #creating 1D array

In [11]:
b = np.array([(1,2,3),(4,5,6)], dtype = float) #creating 2D array

In [13]:
print(a)

[1 2 3]


In [14]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


***Place Holders***

In [15]:
np.zeros((3,4)) #creating 2D Array with 3 Rows, 4 Columns of Zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2,3,4), dtype=np.int16) #Creating 3D Array of Ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.linspace(0,2,9) #Creating array of Evenlyspaced Values so step step

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
np.full((2,2),7) #Creating Constat Array

array([[7, 7],
       [7, 7]])

In [24]:
np.eye(2) #Creating 2X2 Identity Matrix

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2)) #Creating Array with Random Values

array([[0.26237347, 0.65545376],
       [0.57552571, 0.21148971]])

In [26]:
np.empty((3,2)) #Creating Empty Array

array([[1., 2.],
       [3., 4.],
       [5., 6.]])