In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,4,5,6,7,8])

In [4]:
np.split(x, [3,5])

[array([1, 2, 3]), array([4, 4]), array([5, 6, 7, 8])]

= `np.split(x,[3,5])` = `np.split($listname[indisnum,indisnum])`

In [10]:
a,b,c = np.split(x,[3,5]) #Every part is transferring the list variables (a,b,c)

In [11]:
a #Splitted Piece (1rd)

array([1, 2, 3])

In [12]:
b #Splitted Piece (2rd)

array([4, 4])

In [13]:
c #Splitted Piece (3rd)

array([5, 6, 7, 8])

# **Splitting on 2 Dimensions Arrays**

In [19]:
m = np.arange(16).reshape(4,4) #Creating 2Dimensions Array
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Splitting top & under parts by vertical:**

In [24]:
np.vsplit(m,[2]) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [25]:
top,under = np.vsplit(m,[2]) 

In [26]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
under

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Splitting left & rights parts by horizontal:**

In [29]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
left,right = np.hsplit(m,[2])

In [31]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [32]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [39]:
#Hasan Baris GOK from Data Manipulation 101 NumPy Directory on GitHub.