In [1]:
import numpy as np

In [2]:
list = np.array([5,4,6,7,1,2])

In [5]:
np.sort(list) #Sorting

array([1, 2, 4, 5, 6, 7])

In [7]:
list.sort()
list

array([1, 2, 4, 5, 6, 7])

IMPORTANT: If you call the `sort function` as using `numpy sort function`, the array's structure is no change. `(look at 5rd row)`

If you call the `sort function` as using `python sorting`, the array's structure is generally changes. `(look at 7rd row)`

**Sorting the 2 Dimensions Arrays:**

In [13]:
two_dimensions = np.random.normal(20,5,(3,3)) 
#Creating 2D Array 3x3 with nums which are between of 5 and 20.

In [14]:
two_dimensions 

array([[22.61554409, 18.99856791, 19.39216974],
       [24.42002237, 18.09336387, 17.40473016],
       [16.82670246, 11.68949611, 26.34744055]])

In [15]:
np.sort(two_dimensions, axis = 1) 
#Sorting by Rows (axis = 1)

array([[18.99856791, 19.39216974, 22.61554409],
       [17.40473016, 18.09336387, 24.42002237],
       [11.68949611, 16.82670246, 26.34744055]])

In [17]:
np.sort(two_dimensions, axis = 0) 
#Sorting by Columns (axis = 0)

array([[16.82670246, 11.68949611, 17.40473016],
       [22.61554409, 18.09336387, 19.39216974],
       [24.42002237, 18.99856791, 26.34744055]])

In [18]:
#Hasan Baris GOK from Data Manipulation 101 NumPy Directory on GitHub.